[package]
authors = ["Kornel <pornel@pornel.net>"]
categories = ["multimedia::images", "command-line-utilities"]
description = "Library that measures structural similarity between images using a multi-scale variant of the SSIM algorithm."
documentation = "https://docs.rs/dssim-core"
homepage = "https://kornel.ski/dssim"
include = ["README.md", "Cargo.toml", "src/*.rs", "LICENSE"]
keywords = ["ssim", "image", "comparison", "objective", "metric"]
license = "AGPL-3.0"
name = "dssim-core"
readme = "README.md"
repository = "https://github.com/kornelski/dssim.git"
version = "2.11.3"
edition = "2018"

[dependencies]
imgref = "1.6.1"
itertools = "0.9.0"
rayon = "1.3.1"
rgb = "0.8.20"

[dev-dependencies]
lodepng = "3.2.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["parallel"]
parallel = []
